# Generated by Django 3.0.7 on 2020-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
                ('original_price', models.CharField(max_length=200)),
                ('discount_price', models.CharField(max_length=200)),
            ],
        ),
    ]
